{{- $emails := list -}}
{{- range .Values.grafana.authConfig.allowedEmails }}
{{- $email := lower (trim .) -}}
{{- if $email }}
{{- $emails = append $emails (printf "'%s'" $email) -}}
{{- end }}
{{- end }}
{{- $emailList := printf "[%s]" (join ", " $emails) -}}
{{- $roleAttributePath := printf "contains(%s, email) && 'Admin' || contains(%s, preferred_username) && 'Admin' || contains(%s, upn) && 'Admin' || ''" $emailList $emailList $emailList -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-auth
  namespace: grafana
data:
  allowed-emails: {{ join "," .Values.grafana.authConfig.allowedEmails | lower | quote }}
  role-attribute-path: {{ $roleAttributePath | quote }}
